### PR TITLE
Hide stakeout from profile

### PR DESCRIPTION
**Pull request by hvr-lust**

### CODE REVIEW

**Comment by DeKleineKobini** [comment]
I feel like this is something that should be in the actual preferences instead of on the profile itself.

Technically:
- Instead of a `onclick` listener, `addEventListener` is better, but even better would be to use a label instead of a span.
- Storage variables should be added to the default storage too.

**Comment by hvr-lust** [comment]
> I feel like this is something that should be in the actual preferences instead of on the profile itself.
> 
> Technically:
> 
>     * Instead of a `onclick` listener, `addEventListener` is better, but even better would be to use a label instead of a span.
> 
>     * Storage variables should be added to the default storage too.
> 
>     * We don't use `&&`, `||` or `? :` to execute actions, only to get a truthy/falsy value.

Addressed 1 and 3. Add information for 2 in documentation. Part 2 of 1 should be addressed in #526

**Comment by DeKleineKobini** [comment]
> Addressed 1 and 3. Add information for 2 in documentation. Part 2 of 1 should be addressed in #526

Added how to do it in the `CONTRIBUTING.md`. 
"Any setting for a new feature should be defined in torntools/scripts/js/globalFunctions.js in STORAGE."

Will look into testing and further looking at it when I have time, unless @Mephiles does it before me.

**Comment by JiaRS** [comment]
> > Addressed 1 and 3. Add information for 2 in documentation. Part 2 of 1 should be addressed in #526
> 
> Added how to do it in the `CONTRIBUTING.md`.
> "Any setting for a new feature should be defined in torntools/scripts/js/globalFunctions.js in STORAGE."
> 
> Will look into testing and further looking at it when I have time, unless @Mephiles does it before me.

Changes made.

I disagree with having it inside settings configurations. When looking at a profile, I'd like a quick way to check out additional information without an extra refresh. We should bear this in mind when taking on #526 too.

**Comment by hvr-lust** [comment]
> I feel like this is something that should be in the actual preferences instead of on the profile itself.
> 
> Technically:
> 
>     * Instead of a `onclick` listener, `addEventListener` is better, but even better would be to use a label instead of a span.
> 
>     * Storage variables should be added to the default storage too.
> 
>     * We don't use `&&`, `||` or `? :` to execute actions, only to get a truthy/falsy value.

Addressed 1 and 3. Add information for 2 in documentation.

> > Addressed 1 and 3. Add information for 2 in documentation. Part 2 of 1 should be addressed in #526
> 
> Added how to do it in the `CONTRIBUTING.md`.
> "Any setting for a new feature should be defined in torntools/scripts/js/globalFunctions.js in STORAGE."
> 
> Will look into testing and further looking at it when I have time, unless @Mephiles does it before me.

Changed it to label and made it clicky. Not moving it to settings because it causes an unnecessary refresh when I want to view extra info on the fly.

**Comment by DeKleineKobini** [comment]
I'll accept it. We'll decide on how to do it v6 when we get there.

**Pull request merged**
