### PR TITLE
Closes #294

### LINKED ISSUE #294: Adding bazaar item highlight for opening a bazaar url in a new tab
in item market when you select a bazaar the URL gets additional parameters like 'tt_itemid' and 'tt_itemprice'.
i propose to modify the actual URL to add these parameters to support the highlight even when opening the bazaar in a new tab

### PR DESCRIPTION
**Pull request by Sashank999**
Closes #294.

### CODE REVIEW

**Comment by DeKleineKobini** [comment]
[https://www.torn.com/bazaar.php?userId=2108768&tt_itemid=1&tt_itemprice=60&tt_itemid=1&tt_itemprice=60&tt_itemid=1&tt_itemprice=60#/](https://www.torn.com/bazaar.php?userId=2108768&tt_itemid=1&tt_itemprice=60&tt_itemid=1&tt_itemprice=60&tt_itemid=1&tt_itemprice=60#/)

Everytime you open the context menu, it keeps adding it.

**Comment by DeKleineKobini** [comment]
While it no longer keeps adding the params, it also no longer opens the bazaar with the params using the context menu.

**Comment by Sashank999** [comment]
> While it no longer keeps adding the params, it also no longer opens the bazaar with the params using the context menu.

For some reason, the regex doesn't work. So, I used normal _includes()_ .

**Comment by Sashank999** [comment]
For some reason, regex didn't work. I replaced it with `includes()` .

**Pull request merged**
