### PR TITLE
Make travel profit/minute consider stock available

### PR DESCRIPTION
**Pull request by jacklecroy**
Right now, if there's 0 stock available it will still give you the profit/minute of the number you input.

### CODE REVIEW

**Comment by Mephiles** [comment]
I'm unable to check it out myself currently, can you provide visuals of the previous and new behavior? @jacklecroy

**Comment by DeKleineKobini** [comment]
Old:
image

New: 
image

**Comment by Mephiles** [comment]
Hmm, I'm unsure here. When the quantity is 0, I think the user would still like to know the possible profit because most likely the item is in stock when you arrive.

**Comment by DeKleineKobini** [comment]
> Hmm, I'm unsure here. When the quantity is 0, I think the user would still like to know the possible profit because most likely the item is in stock when you arrive.

I thought the same, which is why I didn't merge it immediately. I see the stock as an indicator, seeing whatever gives the most profit even when it's 'out-of-stock' is still useful, as it might be back in stock when you land.

**Comment by jacklecroy** [comment]
Maybe a checkbox to exclude out of stock items then? I like to sort by profit/min and I don't want to see items that are out of stock in that.

**Comment by jacklecroy** [comment]
> 
> 
> > Hmm, I'm unsure here. When the quantity is 0, I think the user would still like to know the possible profit because most likely the item is in stock when you arrive.
> 
> I thought the same, which is why I didn't merge it immediately. I see the stock as an indicator, seeing whatever gives the most profit even when it's 'out-of-stock' is still useful, as it might be back in stock when you land.

I think profit per item should be used for this since per item is unaffected by the quantity available or that you are buying.

**Comment by DeKleineKobini** [comment]
> I think profit per item should be used for this since per item is unaffected by the quantity available or that you are buying.

Profit per item is only available in the advanced view though, which many (including me) don't like for a quick overview.

**Comment by DeKleineKobini** [comment]
I've added an extra filter option in v6, is that fine?

**Comment by Sashank999** [comment]
That is good for v6.
I thought to add that to v5 as a separate filter but it is v5.

**Pull request closed without merging**
