### PR TITLE
new: adds HeLa to revive request targets

### PR DESCRIPTION
**Pull request by dat-mule**
Adds HeLa (https://www.torn.com/factions.php?step=profile&ID=7197) to reviver list

### CODE REVIEW

**Comment by DeKleineKobini** [comment]
Does HeLa have an public place for revives? That's one of our requirements for being added.

**Comment by dat-mule** [comment]
Yes, we have a publicly available discord server + bot request system & respond to private messages as well.

Also a greasemonkey script here: https://greasyfork.org/en/scripts/442606-hela-revives

(I think this all counts as public?)

**Comment by DeKleineKobini** [comment]
The revives that are requested by us, should be available to everyone. Could be behind a role, but it has to be available to everyone to get that role then.

Could you provide a link to the discord?

**Comment by dat-mule** [comment]
If you're asking about the request end: anyone can request a revive - our discord server is here: https://discord.gg/hWamUgW - after verification, /revive and !revive should be available via our bot.

If you're asking about the broadcast end: this primarily broadcasts to the HeLa discord server & doesn't publicly broadcast revive requests anywhere - the audience & ping is limited to HeLa members, as we are independent & aren't part of any larger revive alliances

**Comment by DeKleineKobini** [comment]
It's indeed the broadcast end that is required to be public. We require (and verify compliance regularly) that of every receiver as we want everyone to get a chance to get those requests. It's our one and only requirement for getting added (and an api endpoint ofc, can't request one otherwise).

**Comment by dat-mule** [comment]
We are setup to do that - similar to UHC setup (click emoji for role, etc)

**Comment by DeKleineKobini** [comment]
Looks good.

Before I merge, could you solve the conflict and add yourself in extension/scripts/global/team.js in the TEAM object? That color will also be used in the changelog.

**Comment by dat-mule** [comment]
Should be resolved & ready - thanks!

**Pull request merged**
