### PR TITLE
Change "spe" to "spd"

### PR DESCRIPTION
**Pull request by Sashank999**

### CODE REVIEW

**Comment by Mephiles** [comment]
I'm not sure I agree with this. I think that it's better if all stats are shortened the same way, as in 3 first letters.

**Comment by Sashank999** [comment]
> I'm not sure I agree with this. I think that it's better if all stats are shortened the same way, as in 3 first letters.
But "Spd" rings bells more than "Spe"

**Comment by DeKleineKobini** [comment]
> I'm not sure I agree with this. I think that it's better if all stats are shortened the same way, as in 3 first letters.

Screenshot

**Comment by Mephiles** [comment]
Alright, I'll accept that then :P.

**Pull request merged**
