### PR TITLE
Export API key in local options.

### LINKED ISSUE #565: No import option before entering APIkey
There is no ability to import a backup without first entering your API key, which I think is a bit backwards, since an export most assuredly should also contain information about your API key.

I hop between browsers a lot and I think there should be an option to import my settings without being forced to enter my API key first.

### PR DESCRIPTION
**Pull request by DeKleineKobini**
Closes #565

### CODE REVIEW

**Comment by DeKleineKobini** [comment]
Whether the option has to be enabled by default is still up for debate.

**Comment by Sashank999** [comment]
I think we can just add a checkbox right below the `Export` button to toggle it on/off.

**Comment by DeKleineKobini** [comment]
> I think we can just add a checkbox right below the `Export` button to toggle it on/off.

I already have the checkbox there, but the question is whether those should be checked by default.

**Comment by Sashank999** [comment]
Off. You know, just continuing the previous decision.

**Pull request merged**
