### PR TITLE
Updated wording for all Logistics specials

### PR DESCRIPTION
**Pull request by plushing**
The Logistics Management 3* special mentions contracts. These are Duke mission contracts and not Logistics contracts.

### CODE REVIEW

**Comment by DeKleineKobini** [comment]
What is the wording when in a logistics itself? We use those descriptions.

**Comment by plushing** [comment]
The current TT wording is the same as in Ched's [Logistics announcement](https://www.torn.com/forums.php#/p=threads&t=16098475) and on 3 different pages in the [Torn wiki](https://wiki.torn.com/).

The [company API](https://api.torn.com/torn/40?selections=companies&key=YOUR_KEY) and the company page for employees currently says `2 additional open mission contracts`.

Most of the other Logistics perk descriptions have changed as well.

**Comment by plushing** [comment]
image
I have updated my patch.

**Comment by DeKleineKobini** [comment]
Could you add yourselves in `extension/scripts/global/team.js`, so you can be properly credited?

**Review by DeKleineKobini — APPROVED** [review]

**Pull request merged**
